export const REQUEST_POSTS_LOGIN = 'REQUEST_POSTS_LOGIN';
export const RECEIVE_POSTS_LOGIN = 'RECEIVE_POSTS_LOGIN';
export const FAIL_POSTS_LOGIN = 'FAIL_POSTS_LOGIN';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const REQUEST_POSTS_REGISTER = 'REQUEST_POSTS_REGISTER';
export const RECEIVE_POSTS_REGISTER = 'RECEIVE_POSTS_REGISTER';
export const FAIL_POSTS_REGISTER = 'FAIL_POSTS_REGISTER';
